%% Script group results for pulsatility experiments
%-------------------------------------------------------------------------------
% Data retrieving
%-------------------------------------------------------------------------------
clear all; close all; clc;
addpath(genpath('D:\spm8\toolbox\oct12'))
addpath(genpath('D:\spm8\toolbox\pat12'))
addpath(genpath('D:\Edgar\ssoct\Matlab'))
figsFolder = 'D:\Edgar\Documents\Dropbox\Docs\Carotid';
load('D:\spm8\toolbox\oct12\doppler_color_map.mat')
load('D:\Edgar\Documents\Dropbox\Docs\Carotid\group_data.mat')
%-------------------------------------------------------------------------------

% Vessel diameter threshold
vesselDiamThres = 80;
% Significance level
alpha = 0.05;

%-------------------------------------------------------------------------------
% Statistics: NC=NaCl control, CC=CaCl2 treatment
%-------------------------------------------------------------------------------
% Absolute mean blood speed (mm/s)
NC_speed = abs(NC_stats(:,1));
CC_speed = abs(CC_stats(:,1));
% Blood speed increase (%)
NC_inc = NC_stats(:,6);
CC_inc = CC_stats(:,6);
% Variability from mean (%)
NC_var = NC_stats(:,7);
CC_var = CC_stats(:,7);
% Vessel diameter (um)
NC_diam = NC_stats(:,8);
CC_diam = CC_stats(:,8);
% Heart rate (bpm)
% NC_bpm = NC_stats(:,9);
% CC_bpm = CC_stats(:,9);
% Mouse type (NC=0, CC=1))
% NC_bpm = NC_stats(:,9);
% CC_bpm = CC_stats(:,9);
% Laterality classification
NC_idx_Left = ~logical(NC_stats(:,11));
NC_idx_Right = logical(NC_stats(:,11));
CC_idx_Left = ~logical(CC_stats(:,11));
CC_idx_Right = logical(CC_stats(:,11));
% Vessel diameter classification
NC_idx_Small = NC_diam <= vesselDiamThres;
NC_idx_Big = NC_diam > vesselDiamThres;
CC_idx_Small = CC_diam <= vesselDiamThres;
CC_idx_Big = CC_diam > vesselDiamThres;
%-------------------------------------------------------------------------------

%-------------------------------------------------------------------------------
% Graphics properties
%-------------------------------------------------------------------------------
% Font Sizes
titleFontSize   = 24;
axisFontSize    = 20;
labelFontSize   = 24;
legendFontSize  = 20;
starFontSize    = 36;
mapColor        = [0.5 0.5 0.5; 1 1 1];
%-------------------------------------------------------------------------------

%% blood speed increase & variability stats
% Means
y = [mean([NC_inc  NC_var ]) mean([CC_inc CC_var])];
% Swap columns 2 & 3
% y(:,[2,3]) = y(:,[3,2]);
y = reshape(y,[2 2]);
% SEM (std/sqrt(N))
e = [(std([NC_inc  NC_var ]))./sqrt(numel(NC_var)) (std([CC_inc CC_var]))./sqrt(numel(CC_var))];
% Swap columns 2 & 3
% e(:,[2,3]) = e(:,[3,2]);
e = reshape(e,[2 2]);

%% Plot error bars (blood speed increase & variability)
figure; set(gcf,'color','w')
% colormap
colormap(mapColor)
% Custom bar graphs with error bars (1st arg: error)
barwitherr(e, y)
title('Pulsatility metric','interpreter','none','FontSize',titleFontSize)
set(gca,'FontSize',axisFontSize)
ylabel('%','FontSize',labelFontSize)
set(gca,'XTickLabel',{'Blood speed increase', 'Variability from mean'},'FontWeight', 'b','FontSize',labelFontSize)
legend({'Controls NaCl' 'CaCl_2 induced'},'FontSize',legendFontSize)

%% Save PNG (blood speed increase & variability)
% export_fig(fullfile(figsFolder,'pulsatility_metrics'),'-png',gcf)

%% Heart rate statistics

% % Means
% y = [mean(NC_bpm) mean(CC_bpm)];
% y = [y; 0 0];
% % SEM (std/sqrt(N))
% e = [(std(NC_bpm))./sqrt(numel(NC_bpm)) (std(CC_bpm))./sqrt(numel(CC_bpm))];
% e = [e; 0 0];

%% Plot error bars (Heart rate)
% figure; set(gcf,'color','w')
% % colormap
% colormap(mapColor)
% % Custom bar graphs with error bars (1st arg: error)
% barwitherr(e, y)
% % title('Heart rate','interpreter','none','FontSize',titleFontSize)
% set(gca,'FontSize',axisFontSize)
% ylabel('bpm','FontSize',labelFontSize)
% set(gca,'XTickLabel',{'Heart rate' ''},'FontWeight', 'b','FontSize',labelFontSize)
% xlim([0.5 1.5])
% legend({'Controls NaCl' 'CaCl_2 induced'},'FontSize',legendFontSize)

%% Save PNG (Heart rate)
% export_fig(fullfile(figsFolder,'heart_rate_metrics'),'-png',gcf)

%% Diameter statistics (blood speed increase & variability)

% Two-sample t-test for small vessel diameter in blood speed increase
[TsmallInc.H, TsmallInc.P, TsmallInc.CI, TsmallInc.STATS] = ttest2(...
    NC_inc(NC_diam <= vesselDiamThres), CC_inc(CC_diam <= vesselDiamThres),...
    alpha, 'both');
fprintf('\nN_NC = %d, N_CC = %d p = %0.4f small vessels, blood speed increase \n',...
    numel(NC_inc(NC_diam <= vesselDiamThres)),...
    numel(CC_inc(CC_diam <= vesselDiamThres)), TsmallInc.P);

% Two-sample t-test for bigger vessel diameter in blood speed increase
[TBigInc.H, TBigInc.P, TBigInc.CI,TBigInc.STATS] = ttest2(...
    NC_inc(NC_diam > vesselDiamThres), CC_inc(CC_diam > vesselDiamThres),...
    alpha, 'both');
fprintf('N_NC = %d, N_CC = %d p = %0.4f bigger vessels, blood speed increase \n',...
    numel(NC_inc(NC_diam > vesselDiamThres)),...
    numel(CC_inc(CC_diam > vesselDiamThres)), TBigInc.P);

% Two-sample t-test for small vessel diameter in variability
[TsmallVar.H, TsmallVar.P, TsmallVar.CI, TsmallVar.STATS] = ttest2(...
    NC_var(NC_diam <= vesselDiamThres), CC_var(CC_diam <= vesselDiamThres),...
    alpha, 'both');
fprintf('N_NC = %d, N_CC = %d p = %0.4f small vessels, variability \n',...
    numel(NC_var(NC_diam <= vesselDiamThres)),...
    numel(CC_var(CC_diam <= vesselDiamThres)), TsmallVar.P);

% Two-sample t-test for bigger vessel diameter in variability
[TBigVar.H, TBigVar.P, TBigVar.CI,TBigVar.STATS] = ttest2(...
    NC_var(NC_diam > vesselDiamThres), CC_var(CC_diam > vesselDiamThres),...
    alpha, 'both');
fprintf('N_NC = %d, N_CC = %d p = %0.4f bigger vessels, variability \n',...
    numel(NC_var(NC_diam > vesselDiamThres)),...
    numel(CC_var(CC_diam > vesselDiamThres)), TBigVar.P);

% Means
y = [[mean(NC_inc(NC_diam <= vesselDiamThres)) mean(NC_inc(NC_diam > vesselDiamThres))... 
    mean(NC_var(NC_diam <= vesselDiamThres)) mean(NC_var(NC_diam > vesselDiamThres))];...
    
    [mean(CC_inc(CC_diam <= vesselDiamThres)) mean(CC_inc(CC_diam > vesselDiamThres))...
    mean(CC_var(CC_diam <= vesselDiamThres)) mean(CC_var(CC_diam > vesselDiamThres))]]';

% SEM (std/sqrt(N))
e = [[sem(NC_inc(NC_diam <= vesselDiamThres))...
    sem(NC_inc(NC_diam > vesselDiamThres))... 
    sem(NC_var(NC_diam <= vesselDiamThres))...
    sem(NC_var(NC_diam > vesselDiamThres))];...
    
    [sem(CC_inc(CC_diam <= vesselDiamThres))...
    sem(CC_inc(CC_diam > vesselDiamThres))...
    sem(CC_var(CC_diam <= vesselDiamThres))...
    sem(CC_var(CC_diam > vesselDiamThres))]]';

%% Plot error bars (blood speed increase & variability)
figure; set(gcf,'color','w')
% colormap
colormap(mapColor)
% Custom bar graphs with error bars (1st arg: error)
barwitherr(e, y)
title('Pulsatility metric according to vessel diameter ÿ','interpreter','none','FontSize',titleFontSize)
set(gca,'FontSize',axisFontSize)
ylabel('%','FontSize',labelFontSize)
set(gca,'XTickLabel',{['BSI ÿ<' num2str(vesselDiamThres) 'µm'],...
    ['BSI ÿ>' num2str(vesselDiamThres) 'µm'],...
    ['Var. ÿ<' num2str(vesselDiamThres) 'µm'],...
    ['Var. ÿ>' num2str(vesselDiamThres) 'µm']},...
    'FontWeight', 'b','FontSize',labelFontSize)
legend({'Controls NaCl' 'CaCl_2 induced'},'FontSize',legendFontSize)

%% Save PNG (blood speed increase & variability)
% export_fig(fullfile(figsFolder,'pulsatility_metrics_diameter'),'-png',gcf)

%% Diameter statistics (absolute blood speed)

% Two-sample t-test for small vessel diameter in blood speed increase
[TsmallSpeed.H, TsmallSpeed.P, TsmallSpeed.CI, TsmallSpeed.STATS] = ttest2(...
    NC_speed(NC_idx_Small), CC_speed(CC_idx_Small),...
    alpha, 'both');
fprintf('\nN_NC = %d, N_CC = %d p = %0.4f small vessels, blood speed increase \n',...
    numel(NC_speed(NC_idx_Small)),...
    numel(CC_speed(CC_idx_Small)), TsmallSpeed.P);

% Two-sample t-test for bigger vessel diameter in blood speed increase
[TBigSpeed.H, TBigSpeed.P, TBigSpeed.CI,TBigSpeed.STATS] = ttest2(...
    NC_speed(NC_idx_Big), CC_speed(CC_idx_Big),...
    alpha, 'both');
fprintf('N_NC = %d, N_CC = %d p = %0.4f bigger vessels, blood speed increase \n',...
    numel(NC_speed(NC_idx_Big)),...
    numel(CC_speed(CC_idx_Big)), TBigSpeed.P);

% Means
y = [[mean(NC_speed(NC_idx_Small)) mean(NC_speed(NC_idx_Big))];...
    [mean(CC_speed(CC_idx_Small)) mean(CC_speed(CC_idx_Big))]]';

% SEM (std/sqrt(N))
e = [[sem(NC_speed(NC_idx_Small))...
    sem(NC_speed(NC_idx_Big))];...
    
    [sem(CC_speed(CC_idx_Small))...
    sem(CC_speed(CC_idx_Big))]]';

%% Plot error bars (absolute blood speed)
figure; set(gcf,'color','w')
% colormap
colormap(mapColor)
% Custom bar graphs with error bars (1st arg: error)
barwitherr(e, y)
title('Absolute blood speed according to vessel diameter ÿ','interpreter','none','FontSize',titleFontSize)
set(gca,'FontSize',axisFontSize)
ylabel('|Blood speed| [mm/s]','FontSize',labelFontSize)
set(gca,'XTickLabel',{['ÿ<' num2str(vesselDiamThres) 'µm'],...
    ['ÿ>' num2str(vesselDiamThres) 'µm']},...
    'FontWeight', 'b','FontSize',labelFontSize)
legend({'Controls NaCl' 'CaCl_2 induced'},'FontSize', legendFontSize, 'location', 'northwest')

%% Save PNG (absolute blood speed)
% export_fig(fullfile(figsFolder,'abs_blood_speed_diameter'),'-png',gcf)

%% Two-tailed paired t-test to see inter-hemispheral changes in blood speed
% increase, variability and absolute blood speed 

% Control paired t-test for absolute blood speed in small vessels
[NCTsmallSpeed.H, NCTsmallSpeed.P, NCTsmallSpeed.CI, NCTsmallSpeed.STATS] = ...
    ttest2(NC_speed(NC_idx_Small & NC_idx_Left), NC_speed(NC_idx_Small & NC_idx_Right),...
    alpha, 'both');
fprintf('\nN_NC(Left) = %d, N_NC(Right) = %d p = %0.4f small vessels, abs. blood speed \n',...
    numel(NC_speed(NC_idx_Small & NC_idx_Left)),...
    numel(NC_speed(NC_idx_Small & NC_idx_Right)), NCTsmallSpeed.P);
% Control paired t-test for absolute blood speed in big vessels
[NCTbigSpeed.H, NCTbigSpeed.P, NCTbigSpeed.CI, NCTbigSpeed.STATS] = ...
    ttest2(NC_speed(NC_idx_Big & NC_idx_Left), NC_speed(NC_idx_Big & NC_idx_Right),...
    alpha, 'both');
fprintf('N_NC(Left) = %d, N_NC(Right) = %d p = %0.4f big vessels, abs. blood speed \n',...
    numel(NC_speed(NC_idx_Big & NC_idx_Left)),...
    numel(NC_speed(NC_idx_Big & NC_idx_Right)), NCTbigSpeed.P);

    
% CaCl2 paired t-test for absolute blood speed in small vessels
[CCTsmallSpeed.H, CCTsmallSpeed.P, CCTsmallSpeed.CI, CCTsmallSpeed.STATS] = ...
    ttest2(CC_speed(CC_idx_Small & CC_idx_Left), CC_speed(CC_idx_Small & CC_idx_Right),...
    alpha, 'both');
fprintf('N_CC(Left) = %d, N_CC(Right) = %d p = %0.4f small vessels, abs. blood speed \n',...
    numel(CC_speed(CC_idx_Small & CC_idx_Left)),...
    numel(CC_speed(CC_idx_Small & CC_idx_Right)), CCTsmallSpeed.P);
% CaCl2 paired t-test for absolute blood speed in big vessels
[CCTbigSpeed.H, CCTbigSpeed.P, CCTbigSpeed.CI, CCTbigSpeed.STATS] = ...
    ttest2(CC_speed(CC_idx_Big & CC_idx_Left), CC_speed(CC_idx_Big & CC_idx_Right),...
    alpha, 'both');
fprintf('N_CC(Left) = %d, N_CC(Right) = %d p = %0.4f big vessels, abs. blood speed \n',...
    numel(CC_speed(CC_idx_Big & CC_idx_Left)),...
    numel(CC_speed(CC_idx_Big & CC_idx_Right)), CCTbigSpeed.P);

% Means
y = [[mean(NC_speed(NC_idx_Small & NC_idx_Left))...
    mean(NC_speed(NC_idx_Small & NC_idx_Right))];...
    
    [mean(NC_speed(NC_idx_Big & NC_idx_Left))...
    mean(NC_speed(NC_idx_Big & NC_idx_Right))];...
    
    [mean(CC_speed(CC_idx_Small & CC_idx_Left))...
    mean(CC_speed(CC_idx_Small & CC_idx_Right))];...
    
    [mean(CC_speed(CC_idx_Big & CC_idx_Left))...
    mean(CC_speed(CC_idx_Big & CC_idx_Right))]];

% SEM (std/sqrt(N))
e = [[sem(NC_speed(NC_idx_Small & NC_idx_Left))...
    sem(NC_speed(NC_idx_Small & NC_idx_Right))];...
    
    [sem(NC_speed(NC_idx_Big & NC_idx_Left))...
    sem(NC_speed(NC_idx_Big & NC_idx_Right))];...
    
    [sem(CC_speed(CC_idx_Small & CC_idx_Left))...
    sem(CC_speed(CC_idx_Small & CC_idx_Right))];...
    
    [sem(CC_speed(CC_idx_Big & CC_idx_Left))...
    sem(CC_speed(CC_idx_Big & CC_idx_Right))]];

%% Plot error bars (bilateral absolute blood speed)
figure; set(gcf,'color','w')
% colormap
colormap(mapColor)
% Custom bar graphs with error bars (1st arg: error)
barwitherr(e, y)
title('Bilateral comparison','interpreter','none','FontSize',titleFontSize)
set(gca,'FontSize',axisFontSize)
ylabel('|Blood speed| [mm/s]','FontSize',labelFontSize)
set(gca,'XTickLabel',{['NaClÿ(<' num2str(vesselDiamThres) 'µm)'],...
    ['NaCl(ÿ>' num2str(vesselDiamThres) 'µm)']...
    ['CaCl2(ÿ<' num2str(vesselDiamThres) 'µm)'],...
    ['CaCl2(ÿ>' num2str(vesselDiamThres) 'µm)']},...
    'FontWeight', 'b','FontSize',labelFontSize)
legend({'Left' 'Right'},'FontSize',legendFontSize, 'location', 'northwest')
text(2,0.94,'*','FontWeight', 'b','FontSize', starFontSize)

%% Save PNG (bilateral absolute blood speed)
% export_fig(fullfile(figsFolder,'bilateral_abs_blood_speed'),'-png',gcf)

%% Bilateral blood speed increase
% Control paired t-test for blood speed increase in small vessels
[NCTsmallInc.H, NCTsmallInc.P, NCTsmallInc.CI, NCTsmallInc.STATS] = ...
    ttest2(NC_inc(NC_idx_Small & NC_idx_Left), NC_inc(NC_idx_Small & NC_idx_Right),...
    alpha, 'both');
fprintf('\nN_NC(Left) = %d, N_NC(Right) = %d p = %0.4f small vessels, blood speed increase \n',...
    numel(NC_inc(NC_idx_Small & NC_idx_Left)),...
    numel(NC_inc(NC_idx_Small & NC_idx_Right)), NCTsmallInc.P);
% Control paired t-test for blood speed increase in big vessels
[NCTbigInc.H, NCTbigInc.P, NCTbigInc.CI, NCTbigInc.STATS] = ...
    ttest2(NC_inc(NC_idx_Big & NC_idx_Left), NC_inc(NC_idx_Big & NC_idx_Right),...
    alpha, 'both');
fprintf('N_NC(Left) = %d, N_NC(Right) = %d p = %0.4f big vessels, blood speed increase \n',...
    numel(NC_inc(NC_idx_Big & NC_idx_Left)),...
    numel(NC_inc(NC_idx_Big & NC_idx_Right)), NCTbigInc.P);

    
% CaCl2 paired t-test for blood speed increase in small vessels
[CCTsmallInc.H, CCTsmallInc.P, CCTsmallInc.CI, CCTsmallInc.STATS] = ...
    ttest2(CC_inc(CC_idx_Small & CC_idx_Left), CC_inc(CC_idx_Small & CC_idx_Right),...
    alpha, 'both');
fprintf('N_CC(Left) = %d, N_CC(Right) = %d p = %0.4f small vessels, blood speed increase \n',...
    numel(CC_inc(CC_idx_Small & CC_idx_Left)),...
    numel(CC_inc(CC_idx_Small & CC_idx_Right)), CCTsmallInc.P);
% CaCl2 paired t-test for blood speed increase in big vessels
[CCTbigInc.H, CCTbigInc.P, CCTbigInc.CI, CCTbigInc.STATS] = ...
    ttest2(CC_inc(CC_idx_Big & CC_idx_Left), CC_inc(CC_idx_Big & CC_idx_Right),...
    alpha, 'both');
fprintf('N_CC(Left) = %d, N_CC(Right) = %d p = %0.4f big vessels, blood speed increase \n',...
    numel(CC_inc(CC_idx_Big & CC_idx_Left)),...
    numel(CC_inc(CC_idx_Big & CC_idx_Right)), CCTbigInc.P);

% Means
y = [[mean(NC_inc(NC_idx_Small & NC_idx_Left))...
    mean(NC_inc(NC_idx_Small & NC_idx_Right))];...
    
    [mean(NC_inc(NC_idx_Big & NC_idx_Left))...
    mean(NC_inc(NC_idx_Big & NC_idx_Right))];...
    
    [mean(CC_inc(CC_idx_Small & CC_idx_Left))...
    mean(CC_inc(CC_idx_Small & CC_idx_Right))];...
    
    [mean(CC_inc(CC_idx_Big & CC_idx_Left))...
    mean(CC_inc(CC_idx_Big & CC_idx_Right))]];

% SEM (std/sqrt(N))
e = [[sem(NC_inc(NC_idx_Small & NC_idx_Left))...
    sem(NC_inc(NC_idx_Small & NC_idx_Right))];...
    
    [sem(NC_inc(NC_idx_Big & NC_idx_Left))...
    sem(NC_inc(NC_idx_Big & NC_idx_Right))];...
    
    [sem(CC_inc(CC_idx_Small & CC_idx_Left))...
    sem(CC_inc(CC_idx_Small & CC_idx_Right))];...
    
    [sem(CC_inc(CC_idx_Big & CC_idx_Left))...
    sem(CC_inc(CC_idx_Big & CC_idx_Right))]];

%% Plot error bars (bilateral blood speed increase)
figure; set(gcf,'color','w')
% colormap
colormap(mapColor)
% Custom bar graphs with error bars (1st arg: error)
barwitherr(e, y)
title('Bilateral comparison','interpreter','none','FontSize',titleFontSize)
set(gca,'FontSize',axisFontSize)
ylabel('Blood speed increase [%]','FontSize',labelFontSize)
set(gca,'XTickLabel',{['NaClÿ(<' num2str(vesselDiamThres) 'µm)'],...
    ['NaCl(ÿ>' num2str(vesselDiamThres) 'µm)']...
    ['CaCl2(ÿ<' num2str(vesselDiamThres) 'µm)'],...
    ['CaCl2(ÿ>' num2str(vesselDiamThres) 'µm)']},...
    'FontWeight', 'b','FontSize',labelFontSize)
legend({'Left' 'Right'},'FontSize',legendFontSize, 'location', 'northeast')
text(4,44,'*','FontWeight', 'b','FontSize',starFontSize)

%% Save PNG (bilateral blood speed increase)
% export_fig(fullfile(figsFolder,'bilateral_blood_speed_inc'),'-png',gcf)

%% Bilateral variability
% Control paired t-test for blood speed increase in small vessels
[NCTsmallVar.H, NCTsmallVar.P, NCTsmallVar.CI, NCTsmallVar.STATS] = ...
    ttest2(NC_var(NC_idx_Small & NC_idx_Left), NC_var(NC_idx_Small & NC_idx_Right),...
    alpha, 'both');
fprintf('\nN_NC(Left) = %d, N_NC(Right) = %d p = %0.4f small vessels, variability \n',...
    numel(NC_var(NC_idx_Small & NC_idx_Left)),...
    numel(NC_var(NC_idx_Small & NC_idx_Right)), NCTsmallVar.P);
% Control paired t-test for variability in big vessels
[NCTbigVar.H, NCTbigVar.P, NCTbigVar.CI, NCTbigVar.STATS] = ...
    ttest2(NC_var(NC_idx_Big & NC_idx_Left), NC_var(NC_idx_Big & NC_idx_Right),...
    alpha, 'both');
fprintf('N_NC(Left) = %d, N_NC(Right) = %d p = %0.4f big vessels, variability \n',...
    numel(NC_var(NC_idx_Big & NC_idx_Left)),...
    numel(NC_var(NC_idx_Big & NC_idx_Right)), NCTbigVar.P);
    
% CaCl2 paired t-test for variability in small vessels
[CCTsmallVar.H, CCTsmallVar.P, CCTsmallVar.CI, CCTsmallVar.STATS] = ...
    ttest2(CC_var(CC_idx_Small & CC_idx_Left), CC_var(CC_idx_Small & CC_idx_Right),...
    alpha, 'both');
fprintf('N_CC(Left) = %d, N_CC(Right) = %d p = %0.4f small vessels, variability \n',...
    numel(CC_var(CC_idx_Small & CC_idx_Left)),...
    numel(CC_var(CC_idx_Small & CC_idx_Right)), CCTsmallVar.P);
% CaCl2 paired t-test for variability in big vessels
[CCTbigVar.H, CCTbigVar.P, CCTbigVar.CI, CCTbigVar.STATS] = ...
    ttest2(CC_var(CC_idx_Big & CC_idx_Left), CC_var(CC_idx_Big & CC_idx_Right),...
    alpha, 'both');
fprintf('N_CC(Left) = %d, N_CC(Right) = %d p = %0.4f big vessels, variability \n',...
    numel(CC_var(CC_idx_Big & CC_idx_Left)),...
    numel(CC_var(CC_idx_Big & CC_idx_Right)), CCTbigVar.P);

% Means
y = [[mean(NC_var(NC_idx_Small & NC_idx_Left))...
    mean(NC_var(NC_idx_Small & NC_idx_Right))];...
    
    [mean(NC_var(NC_idx_Big & NC_idx_Left))...
    mean(NC_var(NC_idx_Big & NC_idx_Right))];...
    
    [mean(CC_var(CC_idx_Small & CC_idx_Left))...
    mean(CC_var(CC_idx_Small & CC_idx_Right))];...
    
    [mean(CC_var(CC_idx_Big & CC_idx_Left))...
    mean(CC_var(CC_idx_Big & CC_idx_Right))]];

% SEM (std/sqrt(N))
e = [[sem(NC_var(NC_idx_Small & NC_idx_Left))...
    sem(NC_var(NC_idx_Small & NC_idx_Right))];...
    
    [sem(NC_var(NC_idx_Big & NC_idx_Left))...
    sem(NC_var(NC_idx_Big & NC_idx_Right))];...
    
    [sem(CC_var(CC_idx_Small & CC_idx_Left))...
    sem(CC_var(CC_idx_Small & CC_idx_Right))];...
    
    [sem(CC_var(CC_idx_Big & CC_idx_Left))...
    sem(CC_var(CC_idx_Big & CC_idx_Right))]];

%% Plot error bars (bilateral variability)
figure; set(gcf,'color','w')
% colormap
colormap(mapColor)
% Custom bar graphs with error bars (1st arg: error)
barwitherr(e, y)
title('Bilateral comparison','interpreter','none','FontSize',titleFontSize)
set(gca,'FontSize',axisFontSize)
ylabel('Variability [%]','FontSize',labelFontSize)
set(gca,'XTickLabel',{['NaCl(ÿ<' num2str(vesselDiamThres) 'µm)'],...
    ['NaCl(ÿ>' num2str(vesselDiamThres) 'µm)']...
    ['CaCl2(ÿ<' num2str(vesselDiamThres) 'µm)'],...
    ['CaCl2(ÿ>' num2str(vesselDiamThres) 'µm)']},...
    'FontWeight', 'b','FontSize',labelFontSize)
legend({'Left' 'Right'},'FontSize',legendFontSize, 'location', 'northeast')
% text(4,44,'*','FontWeight', 'b','FontSize',starFontSize)

%% Save PNG (bilateral variability)
% export_fig(fullfile(figsFolder,'bilateral_variability'),'-png',gcf)
