function oct12
% Based on spm_vbm8 from vbm8
% Toolbox wrapper to call oct12 functions
%_______________________________________________________________________________
% Copyright (C) 2012 LIOM Laboratoire d'Imagerie Optique et Moléculaire
%                    École Polytechnique de Montréal
%_______________________________________________________________________________

rev             = '$Rev: 1 $';
SPMid           = spm('FnBanner',mfilename,rev);
[~, Fgraph, ~]  = spm('FnUIsetup','oct12');
spm_help('!ContextHelp',mfilename);
spm_help('!Disp','oct12.man','',Fgraph,'oct12');
fig             = spm_figure('GetWin','Interactive');

% ------------------------------------------------------------------------------
% OCT12 top menu
% ------------------------------------------------------------------------------
h0  = uimenu(fig,...
    'Label',	'oct12',...
    'Separator',	'on',...
    'Tag',		'oct12',...
    'HandleVisibility','off');
% ------------------------------------------------------------------------------


% ------------------------------------------------------------------------------
% Preprocessing
% ------------------------------------------------------------------------------
h1  = uimenu(h0,...
    'Label',	'Preprocessing',...
    'Separator',	'off',...
    'Tag',		'Preprocessing',...
    'HandleVisibility','on');

h1b  = uimenu(h1,...
	'Label',	'Arrange scans in separate folders',...
	'Separator',	'off',...
	'Tag',		'Arrange scans in separate folders',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.preproc.oct_arrange_scans_cfg'');',...
	'HandleVisibility','on');

h1b  = uimenu(h1,...
	'Label',	'Convert Binary files',...
	'Separator',	'off',...
	'Tag',		'Convert Binary files',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.preproc.oct_convert_bin2mat_cfg'');',...
	'HandleVisibility','on');

h1c  = uimenu(h1,...
	'Label',	'Concatenate acqui info files',...
	'Separator',	'off',...
	'Tag',		'Concatenate acqui info files',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.preproc.oct_concatenate_cfg'');',...
	'HandleVisibility','on');
% ------------------------------------------------------------------------------


% ------------------------------------------------------------------------------
% Image Processing
% ------------------------------------------------------------------------------
h2  = uimenu(h0,...
    'Label',	'Image Processing',...
    'Separator',	'off',...
    'Tag',		'Image Processing',...
    'HandleVisibility','on');

h2a  = uimenu(h2,...
	'Label',	'Parameter definition for 3DHD reconstructions',...
	'Separator',	'off',...
	'Tag',		'Parameter definition for 3DHD reconstructions',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.proc.oct_define_3DHD_parameters_cfg'');',...
	'HandleVisibility','on');

h2b  = uimenu(h2,...
	'Label',	'Optimizes dispersion compensation',...
	'Separator',	'off',...
	'Tag',		'Optimizes dispersion compensation',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.proc.oct_dispersion_comp_cfg'');',...
	'HandleVisibility','on');

h2c  = uimenu(h2,...
	'Label',	'Reconstruct structural',...
	'Separator',	'off',...
	'Tag',		'Reconstruct structural',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.proc.oct_reconstruct_struct_cfg'');',...
	'HandleVisibility','on');

h2d  = uimenu(h2,...
	'Label',	'Reconstruct normal doppler',...
	'Separator',	'off',...
	'Tag',		'Reconstruct normal doppler',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.proc.oct_doppler_cfg'');',...
	'HandleVisibility','on');

h2e  = uimenu(h2,...
	'Label',	'Reconstruct angiogram',...
	'Separator',	'off',...
	'Tag',		'Reconstruct angiogram',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.proc.oct_angiogram_cfg'');',...
	'HandleVisibility','on');

h2f  = uimenu(h2,...
	'Label',	'Reconstruct ecg-gated doppler',...
	'Separator',	'off',...
	'Tag',		'Reconstruct ecg-gated doppler',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.proc.oct_ecg_doppler_cfg'');',...
	'HandleVisibility','on');
% ------------------------------------------------------------------------------


% ------------------------------------------------------------------------------
% Image Export
% ------------------------------------------------------------------------------
h3  = uimenu(h0,...
    'Label',	'Image Export',...
    'Separator',	'off',...
    'Tag',		'Image Export',...
    'HandleVisibility','on');

h3a  = uimenu(h3,...
	'Label',	'Create DICOM volume from reconstructions',...
	'Separator',	'off',...
	'Tag',		'Create DICOM volume from reconstructions',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.export.oct_create_dicom_cfg'');',...
	'HandleVisibility','on');

h3b  = uimenu(h3,...
	'Label',	'ROI ECG pulsatility',...
	'Separator',	'off',...
	'Tag',		'ROI ECG pulsatility',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.export.oct_ecg_doppler_cfg'');',...
	'HandleVisibility','on');

h3c  = uimenu(h3,...
	'Label',	'Vessel diameter',...
	'Separator',	'off',...
	'Tag',		'Vessel diameter',...
    'CallBack','spm_jobman(''interactive'','''',''spm.tools.oct12.cfg_oct.export.oct_diameter_vessel_cfg'');',...
	'HandleVisibility','on');

% ------------------------------------------------------------------------------

% EOF
